# This is a message to publish Kayak mode
#
# Kayak_IDLE = 1                  # idle (pause button)
# Kayak_JOYSTICK = 2              # manual control by joystick (pause)
# Kayak_FIXED_MANUVER = 4         # doing one fixed manuver based on param (pause)
# Kayak_HOLD_POSITION = 8         # stopes go to home (stop button)
# Kayak_ABORTED_ONLY_MANUAL = 16  # stop and dont use the hold position (stop)
# Kayak_ABORTED_LPM = 32          # stoped (no battery) only enable comm, NO MOTORS (stop)
# Kayak_CALIBRATION = 64          # in magnetometer calibration mode (no used)
# Kayak_GUIDED_MISSION = 128      # in wp mission mode mode (play)

int64 kayak_mode